### PR TITLE
Add logging for mongo and mysql db 

### PR DESCRIPTION
**Pull request by JGodin-C2C**

### CODE REVIEW

**Comment by mcanevet** [comment]
Isn't logrotate made exactly for this purpose?

**Comment by JGodin-C2C** [comment]
> Isn't logrotate made exactly for this purpose?

Not really the same purpose. Here, this is a single shot command which does not need real history and not a daemon. Just to be able to go back a few days before ( what happened to the backup process ).
Moreover, logrotate would be an external requirement , which is forbiden by the linter. 
J\x00

**Comment by mcanevet** [comment]
"Moreover, logrotate would be an external requirement , which is forbiden by the linter." I'm not sure to understand

**Comment by JGodin-C2C** [comment]
> "Moreover, logrotate would be an external requirement , which is forbiden by the linter." I'm not sure to understand

The linter was pissed when i tried to include tmpreaper in the puppet files, claiming that i should not include  cycling dependencies.

**Comment by cburki** [comment]
And we do not need rotation here, only cleaning up old logs to avoid disk full.

**Comment by saimonn** [comment]
this is very well done with a logrorate rule

**Comment by mfournier** [comment]
@JGodin-C2C I'd rather use the "logging to syslog" pattern. This would make this PR a simple one-line change: `command => '/usr/local/bin/mongodb-backup.sh 2>&1 | logger -t mongodb-backup',`

**Pull request merged**
